"""First batch of non-standard component categories.

Curated for the precision-machining / automation-equipment market that's
PEBS_BOM's primary target. Each entry:

- `id`         stable English slug, used as FK from BOMNode.category_id
- `parameters` schema engineers fill in to fully describe one part
- `common_brands` brand-agnostic list — informational only; the real
  per-customer brand layer (brand_entries) comes later in step 3.5
- `related_gb` left null on purpose for non-std categories (国标件 are
  out-of-scope; engineers don't need help mapping those)

Adding a new category later: append a dict here, run scripts.seed_categories.
The seeder is idempotent — re-running won't duplicate or wipe edits.
"""

from __future__ import annotations

# ─── 5 categories covering Misumi's strongest non-std turf ───────────────
SEED_CATEGORIES: list[dict] = [
    # ─── 1. 直线导轨 ────────────────────────────────────────────────
    {
        "id": "linear_guide",
        "parent_id": None,
        "name_zh": "直线导轨",
        "name_en": "Linear Guide",
        "description": "由导轨 + 滑块组成的高精度直线运动副，是非标自动化设备最常用的导向元件。",
        "parameters": [
            {
                "name": "rail_width",
                "label_zh": "导轨宽度",
                "unit": "mm",
                "type": "enum",
                "values": [9, 12, 15, 20, 25, 30, 35, 45, 55, 65],
                "required": True,
            },
            {
                "name": "rail_length",
                "label_zh": "导轨总长",
                "unit": "mm",
                "type": "number",
                "required": True,
            },
            {
                "name": "slider_count",
                "label_zh": "滑块数量",
                "type": "integer",
                "default": 2,
                "required": True,
            },
            {
                "name": "slider_type",
                "label_zh": "滑块型号",
                "type": "enum",
                "values": ["短型(SR/MR)", "标准(SS/MS)", "加长(SL/ML)", "加长加宽(SLR)"],
                "default": "标准(SS/MS)",
            },
            {
                "name": "preload",
                "label_zh": "预压等级",
                "type": "enum",
                "values": ["Z0(无预压)", "ZA(轻预压)", "ZB(中预压)"],
                "default": "Z0(无预压)",
            },
            {
                "name": "accuracy",
                "label_zh": "精度等级",
                "type": "enum",
                "values": ["N(普通)", "H(高级)", "P(精密)", "SP(超精密)", "UP(顶级)"],
                "default": "H(高级)",
            },
            {
                "name": "rail_count",
                "label_zh": "并行轨数",
                "type": "integer",
                "default": 1,
                "required": False,
            },
        ],
        "common_brands": [
            "HIWIN 上银",
            "THK",
            "NSK",
            "IKO",
            "PMI 银泰",
            "AMT 雅威达",
            "南京工艺",
            "米思米 Misumi",
        ],
        "typical_use": "自动化设备 X/Y/Z 直线运动平台，如 SMT、点胶机、CNC 加工中心、检测台。",
        "related_gb": None,
        "sort_order": 10,
    },
    # ─── 2. 滚珠丝杠 ────────────────────────────────────────────────
    {
        "id": "ball_screw",
        "parent_id": None,
        "name_zh": "滚珠丝杠",
        "name_en": "Ball Screw",
        "description": "把旋转运动转换为高精度直线运动的传动元件，用于精密定位场合。",
        "parameters": [
            {
                "name": "shaft_diameter",
                "label_zh": "丝杠轴径",
                "unit": "mm",
                "type": "enum",
                "values": [8, 10, 12, 14, 16, 20, 25, 32, 40, 50, 63, 80],
                "required": True,
            },
            {
                "name": "lead",
                "label_zh": "导程",
                "unit": "mm",
                "type": "enum",
                "values": [1, 2, 2.5, 5, 10, 16, 20, 25, 32, 40],
                "required": True,
            },
            {
                "name": "total_length",
                "label_zh": "丝杠总长",
                "unit": "mm",
                "type": "number",
                "required": True,
            },
            {
                "name": "stroke",
                "label_zh": "有效行程",
                "unit": "mm",
                "type": "number",
            },
            {
                "name": "accuracy",
                "label_zh": "精度等级",
                "type": "enum",
                "values": ["C10(普通)", "C7(普通精密)", "C5(精密)", "C3(高精密)", "C2(超高精密)"],
                "default": "C5(精密)",
            },
            {
                "name": "preload",
                "label_zh": "预压方式",
                "type": "enum",
                "values": ["无预压", "单螺母预压", "双螺母预压"],
                "default": "单螺母预压",
            },
            {
                "name": "end_machining",
                "label_zh": "两端加工方式",
                "type": "enum",
                "values": ["标准两端加工", "BK/BF 端", "EK/EF 端", "客户图纸"],
                "default": "标准两端加工",
            },
        ],
        "common_brands": [
            "HIWIN 上银",
            "THK",
            "NSK",
            "TBI",
            "PMI 银泰",
            "南京工艺 GZB",
            "汉江机床",
            "米思米 Misumi",
        ],
        "typical_use": "数控机床进给轴、机械手 Z 轴、压机驱动、精密升降平台。",
        "related_gb": None,
        "sort_order": 20,
    },
    # ─── 3. 铝型材 ──────────────────────────────────────────────────
    {
        "id": "aluminum_extrusion",
        "parent_id": None,
        "name_zh": "工业铝型材",
        "name_en": "Aluminum Extrusion",
        "description": "标准化模数铝合金型材，是非标设备机架/防护罩/工作台的主要结构材料。",
        "parameters": [
            {
                "name": "series",
                "label_zh": "系列",
                "type": "enum",
                "values": ["20系列", "30系列", "40系列", "45系列", "50系列", "60系列", "80系列", "90系列", "100系列"],
                "required": True,
            },
            {
                "name": "cross_section",
                "label_zh": "截面规格",
                "type": "enum",
                "values": [
                    "2020", "2040",
                    "3030", "3060", "3090",
                    "4040", "4080", "4040R",
                    "4545", "4590",
                    "5050",
                    "6060", "6090", "60120",
                    "8080", "80160",
                    "9090",
                    "100100",
                ],
                "required": True,
            },
            {
                "name": "length",
                "label_zh": "切割长度",
                "unit": "mm",
                "type": "number",
                "required": True,
            },
            {
                "name": "slot_type",
                "label_zh": "槽型",
                "type": "enum",
                "values": ["欧标(欧6/欧8/欧10)", "国标(国标6/国标8)"],
                "default": "欧标(欧8)",
            },
            {
                "name": "surface",
                "label_zh": "表面处理",
                "type": "enum",
                "values": ["银白阳极氧化", "黑色阳极氧化", "原色拉丝", "其它喷涂"],
                "default": "银白阳极氧化",
            },
            {
                "name": "alloy",
                "label_zh": "材质牌号",
                "type": "enum",
                "values": ["6063-T5", "6061-T6", "其它"],
                "default": "6063-T5",
            },
            {
                "name": "end_machining",
                "label_zh": "端面加工",
                "type": "enum",
                "values": ["切平", "钻孔攻丝", "客户图纸"],
                "default": "切平",
            },
        ],
        "common_brands": [
            "BOSCH Rexroth",
            "ITEM",
            "FATH",
            "SUS",
            "上海荣鹏 RP",
            "广州亿丰 YF",
            "尚品 SP",
            "米思米 Misumi",
        ],
        "typical_use": "设备机架、安全围栏、流水线工作台、机器人外罩。",
        "related_gb": "GB/T 26667（参考）",
        "sort_order": 30,
    },
    # ─── 4. 定位销 ──────────────────────────────────────────────────
    {
        "id": "dowel_pin",
        "parent_id": None,
        "name_zh": "精密定位销",
        "name_en": "Precision Dowel Pin",
        "description": "用于工件、模具、夹具之间高精度位置定位的销轴类零件，区别于国标普通圆柱销。",
        "parameters": [
            {
                "name": "head_type",
                "label_zh": "头部形式",
                "type": "enum",
                "values": ["无头光销", "带头", "外螺纹", "内螺纹拔销", "锥度", "球头"],
                "required": True,
            },
            {
                "name": "diameter",
                "label_zh": "销径",
                "unit": "mm",
                "type": "enum",
                "values": [3, 4, 5, 6, 8, 10, 12, 13, 16, 20, 25, 30],
                "required": True,
            },
            {
                "name": "length",
                "label_zh": "总长",
                "unit": "mm",
                "type": "number",
                "required": True,
            },
            {
                "name": "tolerance",
                "label_zh": "公差",
                "type": "enum",
                "values": ["g6", "h6", "h7", "m6", "n6"],
                "default": "g6",
            },
            {
                "name": "material",
                "label_zh": "材质",
                "type": "enum",
                "values": ["SUJ2 轴承钢", "SUS304", "SUS440C", "SKD11", "SKH51 高速钢", "氮化处理钢"],
                "default": "SUJ2 轴承钢",
            },
            {
                "name": "surface_treatment",
                "label_zh": "表面处理",
                "type": "enum",
                "values": ["原色研磨", "氮化", "镀硬铬", "DLC"],
                "default": "原色研磨",
            },
        ],
        "common_brands": [
            "MISUMI 米思米",
            "PUNCHIND 标点",
            "DAYTON",
            "SANKYO 三协",
            "FIBRO",
        ],
        "typical_use": "夹具定位、模具导向、工装快换基准、CMM 检测夹具。",
        "related_gb": "GB/T 119.1（普通销，仅参考；精密销超出此标）",
        "sort_order": 40,
    },
    # ─── 5. 联轴器 ──────────────────────────────────────────────────
    {
        "id": "coupling",
        "parent_id": None,
        "name_zh": "联轴器",
        "name_en": "Shaft Coupling",
        "description": "连接两根轴并传递扭矩，能补偿少量轴向 / 径向 / 角向偏差。非标设备里电机-丝杠之间的标配。",
        "parameters": [
            {
                "name": "type",
                "label_zh": "联轴器类型",
                "type": "enum",
                "values": [
                    "梅花式(弹性体)",
                    "膜片式",
                    "波纹管式",
                    "十字滑块式(欧氏)",
                    "刚性夹紧式",
                    "弹性套柱销式",
                ],
                "required": True,
            },
            {
                "name": "outer_diameter",
                "label_zh": "外径",
                "unit": "mm",
                "type": "enum",
                "values": [12, 16, 19, 22, 25, 30, 34, 40, 50, 56, 65, 82, 95],
                "required": True,
            },
            {
                "name": "bore_a",
                "label_zh": "A 端孔径",
                "unit": "mm",
                "type": "number",
                "required": True,
            },
            {
                "name": "bore_b",
                "label_zh": "B 端孔径",
                "unit": "mm",
                "type": "number",
                "required": True,
            },
            {
                "name": "rated_torque",
                "label_zh": "额定扭矩",
                "unit": "N·m",
                "type": "number",
            },
            {
                "name": "fastening",
                "label_zh": "固定方式",
                "type": "enum",
                "values": ["夹紧式(无键)", "顶丝(单/双)", "键槽配合"],
                "default": "夹紧式(无键)",
            },
            {
                "name": "material",
                "label_zh": "本体材质",
                "type": "enum",
                "values": ["铝合金 A2017", "不锈钢 SUS303", "黄铜", "工程塑料"],
                "default": "铝合金 A2017",
            },
        ],
        "common_brands": [
            "MIKI PULLEY 三木",
            "KTR",
            "NBK",
            "Rotex/KTR",
            "SUNG-IL 神一",
            "米思米 Misumi",
            "锐马 RIMA",
        ],
        "typical_use": "伺服 / 步进电机轴 与 滚珠丝杠 / 减速机输入轴 之间的连接。",
        "related_gb": None,
        "sort_order": 50,
    },
    # ─── 6. 同步带轮 ────────────────────────────────────────────────
    {
        "id": "timing_belt_pulley",
        "parent_id": None,
        "name_zh": "同步带轮",
        "name_en": "Timing Belt Pulley",
        "description": "配合同步带传递扭矩与精确位置，比链传动更安静、比平皮带更不打滑。非标设备里 X 轴 / Y 轴轻负载传动常用。",
        "parameters": [
            {
                "name": "belt_type",
                "label_zh": "带型",
                "type": "enum",
                "values": ["MXL", "XL", "L", "H", "T2.5", "T5", "T10", "AT5", "AT10", "HTD-3M", "HTD-5M", "HTD-8M", "HTD-14M", "S2M", "S3M", "S5M", "S8M"],
                "required": True,
            },
            {
                "name": "teeth_count",
                "label_zh": "齿数",
                "type": "integer",
                "required": True,
            },
            {
                "name": "belt_width",
                "label_zh": "带宽",
                "unit": "mm",
                "type": "enum",
                "values": [6, 9, 10, 12, 15, 16, 20, 25, 30, 40, 50, 60, 75, 100],
            },
            {
                "name": "bore_diameter",
                "label_zh": "内孔孔径",
                "unit": "mm",
                "type": "number",
                "required": True,
            },
            {
                "name": "bore_type",
                "label_zh": "内孔加工方式",
                "type": "enum",
                "values": ["光孔(成品孔)", "毛胚孔(用户加工)", "键槽孔", "D 形孔"],
                "default": "光孔(成品孔)",
            },
            {
                "name": "flange",
                "label_zh": "挡边",
                "type": "enum",
                "values": ["双边挡边", "单边挡边", "无挡边"],
                "default": "双边挡边",
            },
            {
                "name": "material",
                "label_zh": "材质",
                "type": "enum",
                "values": ["铝合金", "S45C 中碳钢", "SUS304 不锈钢", "工程塑料", "粉末冶金"],
                "default": "铝合金",
            },
        ],
        "common_brands": [
            "三木 MIKI PULLEY",
            "BANDO 阪东",
            "GATES 盖茨",
            "MEGADYNE",
            "CONTITECH 康迪泰克",
            "茂硕 MAOSHUO",
            "致远",
            "米思米 Misumi",
        ],
        "typical_use": "伺服电机 → 同步带 → 滚珠丝杠 / 滑轨座；轻负载位置定位；多轴同步驱动。",
        "related_gb": None,
        "sort_order": 60,
    },
    # ─── 7. 气缸 ────────────────────────────────────────────────────
    {
        "id": "pneumatic_cylinder",
        "parent_id": None,
        "name_zh": "气缸",
        "name_en": "Pneumatic Cylinder",
        "description": "压缩空气驱动的直线动作执行元件，是非标设备里抓取/夹紧/顶升等场景的标配。",
        "parameters": [
            {
                "name": "type",
                "label_zh": "类型",
                "type": "enum",
                "values": ["标准气缸 (SC/SI)", "紧凑型 (CQ/CDQ)", "笔形 (CJ)", "双轴/导杆 (TCM/MGP)", "薄型 (CDU)", "旋转 (CRB)", "无杆 (CY)", "三轴 (MXQ)", "夹爪 (MHZ)", "真空 (吸盘)"],
                "required": True,
            },
            {
                "name": "bore",
                "label_zh": "缸径",
                "unit": "mm",
                "type": "enum",
                "values": [6, 10, 12, 16, 20, 25, 32, 40, 50, 63, 80, 100, 125, 160, 200],
                "required": True,
            },
            {
                "name": "stroke",
                "label_zh": "行程",
                "unit": "mm",
                "type": "number",
                "required": True,
            },
            {
                "name": "cushion",
                "label_zh": "缓冲",
                "type": "enum",
                "values": ["无缓冲", "橡胶缓冲", "气缓冲(可调)"],
                "default": "气缓冲(可调)",
            },
            {
                "name": "magnet",
                "label_zh": "带磁开关",
                "type": "enum",
                "values": ["有", "无"],
                "default": "有",
            },
            {
                "name": "mount",
                "label_zh": "安装方式",
                "type": "enum",
                "values": ["基本型", "L 型支座", "前法兰", "后法兰", "双耳轴", "单耳轴", "底脚 (LB)", "中部摆动"],
                "default": "基本型",
            },
            {
                "name": "rod_thread",
                "label_zh": "活塞杆螺纹",
                "type": "enum",
                "values": ["标准外螺纹", "内螺纹", "客户图纸"],
                "default": "标准外螺纹",
            },
        ],
        "common_brands": [
            "SMC",
            "FESTO 费斯托",
            "AIRTAC 亚德客",
            "KOGANEI 小金井",
            "CKD",
            "TPC",
            "CHELIC 气立可",
            "米思米 Misumi",
        ],
        "typical_use": "夹具夹紧 / 工件顶升 / 物料推送 / 简易机械手抓取。",
        "related_gb": None,
        "sort_order": 70,
    },
    # ─── 8. 编码器 ──────────────────────────────────────────────────
    {
        "id": "encoder",
        "parent_id": None,
        "name_zh": "编码器",
        "name_en": "Encoder",
        "description": "把旋转角度或线性位置转换为电信号反馈给控制器，是闭环运动控制的眼睛。",
        "parameters": [
            {
                "name": "type",
                "label_zh": "类型",
                "type": "enum",
                "values": ["增量式光电", "增量式磁电", "绝对值单圈", "绝对值多圈", "拉线式", "直线光栅尺"],
                "required": True,
            },
            {
                "name": "shaft_diameter",
                "label_zh": "轴径",
                "unit": "mm",
                "type": "enum",
                "values": [4, 5, 6, 8, 10, 12, 14, 15, 20, 25, 30, 38, 50],
            },
            {
                "name": "shaft_type",
                "label_zh": "轴形式",
                "type": "enum",
                "values": ["实心轴", "空心轴(盲孔)", "空心轴(通孔)"],
                "default": "实心轴",
            },
            {
                "name": "resolution",
                "label_zh": "分辨率",
                "type": "string",
                "required": True,
            },
            {
                "name": "output",
                "label_zh": "输出类型",
                "type": "enum",
                "values": ["TTL/RS422", "HTL/Push-Pull", "开漏 NPN", "Voltage", "SSI", "EnDat", "BiSS-C", "PROFINET", "EtherCAT"],
                "default": "HTL/Push-Pull",
            },
            {
                "name": "power",
                "label_zh": "供电",
                "type": "enum",
                "values": ["5VDC", "12VDC", "24VDC", "5-30VDC 宽压"],
                "default": "5-30VDC 宽压",
            },
            {
                "name": "ip_rating",
                "label_zh": "防护等级",
                "type": "enum",
                "values": ["IP54", "IP65", "IP67"],
                "default": "IP65",
            },
        ],
        "common_brands": [
            "HEIDENHAIN 海德汉",
            "RENISHAW 雷尼绍",
            "OMRON 欧姆龙",
            "KOYO 光洋",
            "AUTONICS 奥托尼克斯",
            "SICK",
            "TR-Electronic",
            "长春禹衡",
            "长春长光",
        ],
        "typical_use": "伺服电机末端反馈 / 滚珠丝杠位置反馈 / 转盘分度反馈 / 精密计米。",
        "related_gb": None,
        "sort_order": 80,
    },
    # ─── 9. 接近开关 ────────────────────────────────────────────────
    {
        "id": "proximity_sensor",
        "parent_id": None,
        "name_zh": "接近开关",
        "name_en": "Proximity Sensor",
        "description": "无接触检测目标物存在/位置的开关传感器，自动化设备里用于工件到位、限位等场景。",
        "parameters": [
            {
                "name": "type",
                "label_zh": "感应方式",
                "type": "enum",
                "values": ["电感式(金属)", "电容式(任意材质)", "磁性式(气缸专用)", "超声波式", "光电对射", "光电反射"],
                "required": True,
            },
            {
                "name": "shape",
                "label_zh": "外形",
                "type": "enum",
                "values": ["圆柱 M8", "圆柱 M12", "圆柱 M18", "圆柱 M30", "方形/扁平", "槽型", "贴片"],
                "required": True,
            },
            {
                "name": "detection_distance",
                "label_zh": "检测距离",
                "unit": "mm",
                "type": "number",
                "required": True,
            },
            {
                "name": "output",
                "label_zh": "输出形式",
                "type": "enum",
                "values": ["NPN 常开", "NPN 常闭", "PNP 常开", "PNP 常闭", "AC 两线", "Namur 本安"],
                "default": "PNP 常开",
            },
            {
                "name": "power",
                "label_zh": "供电",
                "type": "enum",
                "values": ["10-30VDC", "24VDC", "12VDC", "AC 90-250V"],
                "default": "10-30VDC",
            },
            {
                "name": "connection",
                "label_zh": "接线方式",
                "type": "enum",
                "values": ["3 线", "4 线", "2 线", "M8 接插件", "M12 接插件", "电缆引出"],
                "default": "M12 接插件",
            },
            {
                "name": "ip_rating",
                "label_zh": "防护等级",
                "type": "enum",
                "values": ["IP65", "IP67", "IP68", "IP69K"],
                "default": "IP67",
            },
        ],
        "common_brands": [
            "OMRON 欧姆龙",
            "SICK",
            "BALLUFF 巴鲁夫",
            "PEPPERL+FUCHS 倍加福",
            "AUTONICS 奥托尼克斯",
            "FOTEK 阳明",
            "TURCK 图尔克",
            "SCHNEIDER 施耐德",
        ],
        "typical_use": "工件到位检测 / 气缸活塞位置反馈 / 物料计数 / 安全门检测。",
        "related_gb": None,
        "sort_order": 90,
    },
    # ─── 10. 减速机 ─────────────────────────────────────────────────
    {
        "id": "gearbox",
        "parent_id": None,
        "name_zh": "减速机",
        "name_en": "Gearbox / Reducer",
        "description": "降低输入转速、放大扭矩的传动装置。非标设备里和伺服电机配套用于高扭矩/低速工况。",
        "parameters": [
            {
                "name": "type",
                "label_zh": "类型",
                "type": "enum",
                "values": ["行星减速机", "谐波减速机", "RV 减速机", "斜齿轮", "蜗轮蜗杆", "平行轴硬齿面", "直角轴", "摆线针轮"],
                "required": True,
            },
            {
                "name": "frame_size",
                "label_zh": "机座号",
                "type": "enum",
                "values": ["40", "60", "80", "90", "100", "120", "142", "180", "220", "260"],
                "required": True,
            },
            {
                "name": "ratio",
                "label_zh": "减速比",
                "type": "enum",
                "values": ["3:1", "5:1", "8:1", "10:1", "15:1", "20:1", "25:1", "30:1", "40:1", "50:1", "70:1", "100:1", "120:1", "其它"],
                "required": True,
            },
            {
                "name": "backlash",
                "label_zh": "回差",
                "type": "enum",
                "values": ["标准 P3 (≤10')", "精密 P2 (≤6')", "高精度 P1 (≤3')", "超精密 P0 (≤1')"],
                "default": "精密 P2 (≤6')",
            },
            {
                "name": "input_type",
                "label_zh": "输入端形式",
                "type": "enum",
                "values": ["伺服法兰直连", "通用电机法兰", "输入轴外伸", "输入轴双伸"],
                "default": "伺服法兰直连",
            },
            {
                "name": "output_type",
                "label_zh": "输出端形式",
                "type": "enum",
                "values": ["实心轴", "空心轴", "法兰", "方形输出盘", "渐开线花键"],
                "default": "实心轴",
            },
            {
                "name": "ip_rating",
                "label_zh": "防护等级",
                "type": "enum",
                "values": ["IP54", "IP65"],
                "default": "IP54",
            },
        ],
        "common_brands": [
            "HARMONIC DRIVE 哈默纳科",
            "NABTESCO 纳博特斯克",
            "NIDEC SHIMPO 日本电产",
            "SUMITOMO 住友",
            "NEUGART 纽卡特",
            "APEX 精锐",
            "WITTENSTEIN 威腾",
            "中大同步",
            "LEISHEN 来福",
            "紫光",
        ],
        "typical_use": "伺服电机 → 减速机 → 转盘/丝杠/滑台/机械臂关节。",
        "related_gb": None,
        "sort_order": 100,
    },
]
